### ISSUE TITLE
互测阶段的“待测试代码”指什么

### ISSUE THREAD

**Issue by findmenowhere** [OO-guide-2019/oo-rules#1]
请问互测阶段，”待测试代码“是指同一组内所有组员的代码吗？
即可以下载所有组员的代码？

**Comment by PaParaZz1** [comment]
同一组内，是可以下载所有组员的代码。你提交的一个样例如果有效将会对组内所有的人进行测试。我们这样设计是为了减少以前一对一互测的偶然性，玩家可以任意选择一份或几份代码进行阅读，来寻找其中的错误，帮助构造测试样例。

**Comment by PaParaZz1** [comment]
另外，提问时建议采用讨论区文档中规定的那种形式。(看起来好看

**Comment by findmenowhere** [comment]
谢谢助教！下次一定注意标题格式！
