### ISSUE TITLE
关于solid与shared样例的判断、计数及其对bug修复分数的影响

### ISSUE THREAD

**Issue by login256** [OO-guide-2019/oo-rules#2]
关于shared样例的判断在“互测文档”中，表述是

> 如果被测者**能够在一次合并bug修复中同时修复了两个bug**，则该bug对于被测者而言，视为同质测试用例，只被扣除一次分数

在这里，solid和shared是针对被测试者而言的。但是，在计算bug奖励分时，描述的是“**该测试者提供的**"，计算时是针对提供者来计算个数的。
因此，如果样例提供者提供的一个样例 用于多个人，但是在不同的人处solid和shared的情况不同，此时判断的方法是怎样的呢。

当然也有可能这里我的理解不对，因此希望可以对于此有一些详细的描述。

谢谢助教了。

**Comment by PaParaZz1** [comment]
首先，一点要记住**shard和solid是针对被测试者的**。在互测文档原文中提及了：

> 进一步讲，如果某个被测者被报告了两个bug，且该被测者无法在一次合并bug修复中同时解决这两个bug，那么无论本bug在他人的程序中是否被视为同质bug，对于本被测者而言，这仍然是两个bug，被扣的分数按两个bug计算。


这里说明了提供的一个样例A 用于多个人时要分开处理，但确实没有明显的说奖励分。
关于奖励分，应该是按照被测者的情况分开处理，比如A成功hack了B，C，D三个人，在B处是solid，在C,D处是shared，则A从B这里拿到的奖励分按solid算一份，在C，D这里按照各自的shared比例进行计算。
bug奖励分的说明部分确实存在一点歧义，修正后应该为：
**bug奖励分 = 该测试者提供的样例被视为solid的个数 * 对应基准分 + 该测试者提供的样例被视为shared时对应的奖励分总和**

**Comment by PaParaZz1** [comment]
如果你认可这个新表述更明确，请回复，我会及时在规则文档中更新

**Comment by login256** [comment]
看明白了，这个表述应该很明确了，谢谢助教！
