### ISSUE TITLE
关于bug修复作弊的问题

### ISSUE THREAD

**Issue by ArcheyChen** [OO-guide-2019/oo-rules#3]
在bug修复细则文档中，有提到禁止打表型修复。

但是，如果还没进入互测阶段，就自己发现了bug。然后自己用打表型写法解决了某些问题。

这种情况允许吗

**Comment by PaParaZz1** [comment]
规则文档中说的打表型修复，是指我们会对比bug修复前后的改动内容，如果改动内容中出现打表，我们会做进一步审查，如果你提交到互测的代码中有”打表“内容，应该是允许的，因为特殊情况的特判是允许的。
