### ISSUE TITLE
【关于规则】邮箱设定相关

### ISSUE THREAD

**Issue by AIflowerQ** [OO-guide-2019/oo-rules#4]
gitlab中的账号有一个以学号来生成的邮箱，但是实际上本人并没有这么一个邮箱。
此外，寒假作业的提交是利用这个并不存在的邮箱连接远程库，并且成功。
请问，1、这个邮箱可否改为本人qq邮箱
           2、如果不更改为一个真实存在的邮箱是否会有弊端

**Comment by PaParaZz1** [comment]
首先非常感谢终于有同学使用我写的讨论区分类标记了！！！
然后关于你的问题：
1. gitlab上个人信息部分，邮箱，用户名，头像都可以自由更改
2. 没有弊端，这只是一个登陆用的记号，系统和gitlab的对应是通过你的User ID实现的，这个键是无法修改的。
